Added -m flag to grep for record values to deal with multiple records with same name causing unneeded zonefile updates; added error check for external IP discovery

diff --git a/gad b/gad
--- a/gad
+++ b/gad
@@ -121,7 +121,7 @@ create() {
 
 check() {
   while [ ! -z "$1" ]; do
-    record_value=`rpc "domain.zone.record.list" "int" "$zone_id" "int" "0" "struct" "name" "string" "$1" | grep -A 1 ">value<" | sed -n 's/.*<string>\([0-9]*\.[0-9]*\.[0-9]*\.[0-9]*\).*/\1/p'` > /dev/null 2>&1
+    record_value=`rpc "domain.zone.record.list" "int" "$zone_id" "int" "0" "struct" "name" "string" "$1" | grep -m 1 -A 1 ">value<" | sed -n 's/.*<string>\([0-9]*\.[0-9]*\.[0-9]*\.[0-9]*\).*/\1/p'` > /dev/null 2>&1
     if [ -z "$record_value" ]; then
       if [ -z "$records_to_create" ]; then
         records_to_create="$1"
@@ -146,6 +146,10 @@ if [ ! -z "$ext_if" ]; then
 else
   ext_ip_method="OpenDNS"
   ext_ip=`dig +short @resolver1.opendns.com myip.opendns.com`
+fi
+if [ -z "$ext_ip" ]; then
+  echo "Failed to determine external IP address with "$ext_ip_method". See above error."
+  exit 1
 fi
 
 # Get the active zonefile for the domain
